#Barcode Management Program
"""This program takes in input data (Name,Price and Date) and uses the hashlib module to convert the input data into hexadecimal version of a fixed size (3+3+3 bytes) and converts it into binary.
A barcode is generated by assigning 0's to "│"(Unicode Character : U+2502) and assigning 1's to "▌"(Unicode Character : U+258C).
█││  is the start code which lets the scanner know where to start and   █▌│█ is the end code which lets the scanner know where 
to end scanning.This Program does not use any traditional barcode algorithms. We will have to create our own scanner inorder to use this program in a practical environment"""
import hashlib
def Barcode_Generator(Name,Price,Date):
    Encoded_Name,Encoded_Price,Encoded_Date=bin(int((hashlib.blake2s(Name.encode('utf-8'),digest_size=3)).hexdigest(),16))[2:],bin(int((hashlib.blake2s(Price.encode('utf-8'),digest_size=3)).hexdigest(),16))[2:],bin(int((hashlib.blake2s(Date.encode('utf-8'),digest_size=3)).hexdigest(),16))[2:]
    #The digest size is 3 since 3 bytes results in 6 hexadecimal digits (1 byte = 2 hexadecimal digits) which on further convertion into binary results in 24 binary digits.'utf-8' is used for unicode character support
    Checksum=bin(((int(Encoded_Name,2)+int(Encoded_Date,2)+int(Encoded_Price,2)))%128)[2:]  #Checksum ensures a good amount of precision for scanning the barcode. Once the scanner scans the barcode, the scanner will recalculate the checksum from the data it has read. if the checksum does not match with the checksum it read, the match will fail
    Checksum=(7-len(Checksum))*"0"+Checksum #This is to ensure constant length of checksum value
    Barcode_Binary=f"{('0'*(24-len(Encoded_Name)))+Encoded_Name} {('0'*(24-len(Encoded_Price)))+Encoded_Price} {('0'*(24-len(Encoded_Date)))+Encoded_Date} {Checksum}"
    Barcode="█││  "+Barcode_Binary.replace("0","│").replace("1","▌")+"  █▌│█"# │ --> unicode character : U+2502      ▌ --> unicode character : U+258C
    """ █││  is the start code which lets the scanner know where to start and   █▌│█ is the end code which lets the scanner know where to end scanning
    the start code consists of ' █,│ and │ ' █ --> unicode character : U+2588  │ --> unicode character : U+2502
    the end code consists of ' █,▌,│ and █ ' █ --> unicode character : U+2588  ▌ --> unicode character : U+258C  │ --> unicode character : U+2502"""
    Barcode_Binary=Barcode_Binary.replace(" ","")
    Barcode_Decimal=int(Barcode_Binary,2)
    return (Barcode,Barcode_Binary,Barcode_Decimal)
def Print_Barcode(Name,Price,Date,Barcode,Hexadecimal_Code,Name_Filler="",Price_Filler="",Date_Filler=""):
    Filler=""
    for i in [Name_Filler,Price_Filler,Date_Filler]:
        if len(i)>len(Filler):
            Filler=i
    print(f"""
        {"="*(len(Barcode)+2)}

         {Name_Filler}Name : {Name}
         {Price_Filler}Price : {Price}
         {Date_Filler}Production Date : {Date}

         {"-"*(11+len(Filler))}
          {Filler}Barcode : 
         {"-"*(11+len(Filler))}
        
        """,f"\n\t {Barcode}"*7,"\n\t "+(" "*((len(Barcode)-len(" ".join(Hexadecimal_Code)))//2))+" ".join(Hexadecimal_Code.upper()),f"""

        {"="*(len(Barcode)+2)}
        """)
def Sort_Items(Data):
    #Uses the Bubble sort mechanism
    Data=list(Data.items())
    for i in range(len(Data)-1):
        for j in range(len(Data)-i-1):
            if Data[j][1][0][0]>Data[j+1][1][0][0]:
                Data[j],Data[j+1]=Data[j+1],Data[j]
    Data=dict(Data)
    return Data
def Validate_Date(Date):
    Date_chr,Chosen_chr,chr_chosen=0,"",False
    for i in Date:
        if i.isdigit():
            continue
        elif i in "/.-_ ":#Handles seperator based inputs for dates
            Date_chr+=1
            if not chr_chosen:
                Chosen_chr,chr_chosen=i,True
            elif i!=Chosen_chr:
                break
            if Date_chr==3:
                break
        elif i.isalpha():#Handles Text Based inputs for date
            Months={("January","Jan",31):"01",("February","Feb",28):"02",("March","Mar",31):"03",("April","Apr",30):"04",("May","May",31):"05",("June","Jun",30):"06",("July","Jul",31):"07",("Augu","Aug",31):"08",("September","Sept",30):"09",("October","Oct",31):"10",("November","Nov",30):"11",("December","Dec",31):"12"}
            Date=(Date.lower().replace("st","").replace("nd","").replace("rd","").replace("th","").replace(",","").replace(".","").title()).split()                                         #We Have Augu instead of August since the 'st' in August will get replaced
            New_Date=["","",""]
            Days=0
            if len(Date)!=3:
                return (Date,False)
            for j in range(3):#range(3) since the text format includes 3 sections(day month year or month day year)
                if j==2:
                    if Date[2].isdigit():
                        if len(Date[2])==2:
                            New_Date[2]="20"+Date[2]
                            continue
                        elif len(Date[2])==4:
                            New_Date[2]=Date[2]
                            continue
                        else:
                            return (Date,False)
                    else:
                        return (Date,False)
                elif Date[j].isalpha():
                    for k in Months:
                        if Date[j] in k:
                            New_Date[1],Days=Months.get(k),k[2]
                            break
                    else:
                        return(Date,False)
                else:
                    if len(Date[j])==2 and Date[j].isdigit():
                        New_Date[0]=Date[j]
                    elif len(Date[j])==1 and Date[j].isdigit():
                        New_Date[0]="0"+Date[j]
            Date=New_Date[0]+"/"+New_Date[1]+"/"+New_Date[2]
            if New_Date[1]=="02" and int(New_Date[2])%4==0:#Handles Leap Year Logic
                Days=29
            if int(Date[:2])>Days or int(Date[3:5])>12:
                return (Date,None)
            if len(Date)==10:
                return (Date,True)
        else:
                break
    else:
        Days={1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
        if chr_chosen:
            """"Data_map contains the possibilities that can result in valid date processing.
            This is the format for the Date_map dictionary: 
                Date_map={(1st separator index,2nd seperator index):(Possible lengths)}"""
            Date_map={(2,5):(8,10),(1,3):(6,8),(2,4):(7,9),(1,4):(7,9)}
            First_chr_index=Date.find(Chosen_chr)#The chr index refers to the index of the seperator used by the user
            Second_chr_index=Date.find(Chosen_chr,First_chr_index+1)
            if Second_chr_index==-1:
                return (Date,False)
            for i in Date_map:
                if (i==(First_chr_index,Second_chr_index)) and (len(Date) in Date_map.get(i)):
                    if Chosen_chr!="/":
                        Date=Date.replace(Chosen_chr,"/")
                    if First_chr_index==1:
                        Date="0"+Date
                        First_chr_index+=1
                        Second_chr_index+=1
                    if (Second_chr_index-First_chr_index)==2:
                        Date=Date[:Second_chr_index].replace("/","/0")+Date[Second_chr_index:]
                        Second_chr_index+=1
                    if (len(Date)-Second_chr_index)==3:
                        Date=Date[:First_chr_index+1]+Date[First_chr_index+1:].replace("/","/20")
                    if (int(Date[3:5])==2 and int(Date[6:])%4==0):
                        Days[2]=29
                    if int(Date[:2])>Days.get(int(Date[3:5])) or int(Date[3:5])>12:
                        return(Date,None)
                    return (Date,True)
        else:
            if len(Date) in [4,6,8]:#handles inputs like 1125 or 1 1 25 or 010125 or 01 01 25 which is later formatted into 01/01/2025
                if len(Date)==4:
                    Date="0"+Date[0]+"/0"+Date[1]+"/20"+Date[2:]
                    #len=4 for 1/1/25
                elif len(Date)==6:
                    Date=Date[:2]+"/"+Date[2:4]+"/20"+Date[4:]
                    #len=6 for 01/01/25
                elif len(Date)==8:
                    Date=Date[:2]+"/"+Date[2:4]+"/"+Date[4:]
                    #len=8 for 01/01/2025
                if (int(Date[3:5])==2 and int(Date[6:])%4==0):
                    Days[2]=29
                if int(Date[:2])>Days.get(int(Date[3:5])) or int(Date[3:5])>12:
                        return(Date,None)
                return (Date,True)
    return (Date,False)
def Validate_Price(Price):
    if Price=="":
        Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
        return (False,"")
    try:
        message_printed=False
        if ("XX" in Price):
            raise Exception
        for j in Price:
            if j not in "1234567890.+-/*()%^X ":
                raise Exception
            if j=="^":
                Price=Price.replace("^","**")
            if j in "X":
                Price=Price.replace("X","*")
        Price=str(float(eval(Price)))
        #The eval function is used to make the price field have a calculator feature
        if float(Price)<0:
            Message("You cannot enter a negative value!",":")
            message_printed=True
            raise Exception
    except ZeroDivisionError:
        Message("YOU CANNOT DIVIDE BY ZERO!",":")
        return (False,"")
    except OverflowError:
        Message("THE NUMBER IS TOO LARGE!",":")
        return(False,"")
    except:
        if not message_printed:
            Message("INVALID INPUT!",":")
        return (False,"")
    else:
        return (True,Price)
def Message(Message,Decoration):
    print(f"""
        {Decoration*(len(Message)+4)}
        | {Message} |
        {Decoration*(len(Message)+4)}
            """)
def Create_Barcode(Data):
    Decision,Name,Price,Date="YES","","",""
    Message("Note:Type 'go back' if you would like to go back from any operation","-")
    while Decision.startswith("Y"):
        if len(Data)==0:
            go_back=False
        else:
            go_back=True
        while Name=="" or Price=="GOBACK":
            Name=" ".join(input(f"\n\t Enter the name of the product : ").strip().lower().title().split())
            if Name=="":
                Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
            else:
                Price=""
                break
        if Name=="Go Back":
            if go_back==True:
                Message("OPERATION CANCELLED!","-")
                break
            else:
                Message("CANNOT GO TO THE MENU AS WE CANNOT PERFORM ANY OPERATION WITHOUT ANY PREVIOUSLY STORED DATA!",":")
                Name=""
                continue
        Found=False
        for i in Data:
            if Name==(Data.get(i))[0]:
                Question=input("\n\t This product already exists , do u want to make changes to the product ? Yes/No ").strip().upper()
                if Question.startswith("Y"):
                    Decision="No"
                    Update_Barcode(Data,Name)
                else:
                    Decision,Name,Price,Date=input("\n\t Would you like to create barcode for another product ? Yes/No ").strip().upper(),"","",""
                Found=True
                break
        if Found:
            if Decision.startswith("Y"):
                continue
            else:
                break
        while Price=="" or " ".join(Date.lower().split())=="go back":
            Price="".join(input("\n\t Enter the price of the product (Only Digits) : ").strip().upper().split())
            if Price=="GOBACK":
                break
            Price_Status,Price=Validate_Price(Price)
            if Price_Status==True:
                Date=""
                break
        if Price=="GOBACK":
            continue
        while True:
            Date=input("\n\t Enter production date of the product (Enter in dd/mm/yy or text format [Example: 1st Jan 2025] ) : ").strip()
            if Date=="":
                Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
                continue
            if " ".join(Date.lower().split())=="go back":
                break
            Date,Valid_date=Validate_Date(Date)
            if Valid_date==True:
                break
            elif Valid_date==False:
                Message("INVALID INPUT! [Enter in dd/mm/yy or text format (Example : 1st Jan 2025)]",":")
            elif Valid_date==None:
                Message("INVALID DATE! [The date you have entered does not exist!]",":")
        if " ".join(Date.lower().split())=="go back":
            continue
        Barcode,Barcode_Binary,Barcode_Decimal=Barcode_Generator(Name,Price,Date)
        Data[Barcode_Binary]=[Name,Price,Date,Barcode]
        Print_Barcode(Name,Price,Date,Barcode,hex(Barcode_Decimal)[2:].upper())
        Save_Overall_Data(Data)
        Decision,Name,Price,Date=input("\n\t Would you like to create a barcode for another product ? Yes/No ").strip().upper(),"","",""
def Search_Barcode(Data,Employee=False):
    Decision="YES"
    while Decision.startswith("Y"):
        if len(Data)==0:
            Message("CANNOT SEARCH ANY DATA SINCE NO DATA IS FOUND!",":")
            break
        Found=False
        Search_Decision=input(f"""
        {"-"*24}
         Search using :
             1.Products Name
             2.Hexadecimal/Binary Code
             3.Exit
         Enter an option (1-3) : """).strip().lower().replace(".","").replace("'","").replace(",","").replace("/","").replace(" ","")
        print("\n\t ","-"*24)
        if Search_Decision in ["1","productsname","name","1productsname","1name","2","hexadecimalcode","hexadecimal","2hexadecimalcode","2hexadecimal","code","2code"]:
            Message("Note:Type 'go back' if you would like to go back from any operation","-")
        if Search_Decision in ["1","productsname","name","1productsname","1name"]:
            while True:
                Name=" ".join(input("\n\t Enter product's Name : ").strip().lower().title().split())
                if Name=="":
                    Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
                    continue
                else:
                    break
            if Name=="Go Back":
                Message("OPERATION CANCELLED!","-")
                continue
            for key,value in Data.items():
                if Name==value[0]:
                    Found,Price,Date,Barcode,Product_Code=True,value[1],value[2],value[3],hex(int(key,2))[2:].upper()
                    break
        elif Search_Decision in ["2","hexadecimalbinarycode","2hexadecimalbinarycode","hexadecimalcode","hexadecimal","2hexadecimalcode","2hexadecimal","code","2code","binarycode","2binarycode","binary","2binary"]:
            while True:
                Code="".join(input("\n\t Enter product's Hexadecimal/Binary Code : ").strip().upper().split())
                if Code=="":
                    Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
                    continue
                else:
                    break
            if Code=="GOBACK":
                Message("OPERATION CANCELLED!","-")
                continue
            try:
                if Code.count("1")+Code.count("0")!=len(Code) or len(Code)<=20:
                    Code=bin(int(Code,16))[2:]
                Code="0"*(79-len(Code))+Code
            except:
                Message("Invalid Input!",":")
                continue
            if Code in Data:
                Found,Product_Code=True,hex(int(Code,2))[2:]
                Name,Price,Date,Barcode=Data.get(Code)
        elif Search_Decision in ["3","exit","3exit","quit","3quit"]:
            Message("OPERATION CANCELLED!","-")
            break
        else:
            Message("PLEASE ENTER A VALID OPTION (1-3)!",":")
            continue
        if Found:
            Print_Barcode(Name,Price,Date,Barcode,Product_Code)
            if Employee==True:
                logs(f"Employee has searched for {Name}")
        else:
            Message("PRODUCT NOT FOUND!",":")
        Decision=input("\n\t Would you like to search for another product's barcode? Yes/No ").strip().upper()
def Delete_Barcode(Data):
    Decision="YES"
    while Decision.startswith("Y"):
        if len(Data)==0:
            Message("CANNOT DELETE ANY DATA SINCE NO DATA IS FOUND!",":")
            break
        Message("Note:Type 'go back' if you would like to go back from any operation","-")
        while True:
            Name=" ".join(input("\n\t Enter product Name : ").strip().lower().title().split())
            if Name=="":
                Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
                continue
            else:
                break
        if Name=="Go Back":
            Message("OPERATION CANCELLED!","-")
            break
        Confirm=input("\n\t Are you sure ? Yes/No ").strip().upper()
        if not Confirm.startswith("Y"):
            Message("DATA REMOVAL CANCELLED","-")
            break
        Delete_key=None
        for key,value in Data.items():
            if Name==value[0]:
                Delete_key=key
                break
        else:
            Message("PRODUCT NOT FOUND!",":")
        if Delete_key:
            del Data[Delete_key]
            Message(f"{Name} has been successfully deleted","-")
            Save_Overall_Data(Data)
        Decision=input("\n\t Would you like to delete a barcode of another product ? Yes/No ").strip().upper()
def Update_Barcode(Data,Name=None):
    Decision="YES"
    while Decision.startswith("Y"):
        if len(Data)==0:
            Message("CANNOT UPDATE ANY DATA SINCE NO DATA IS FOUND!",":")
            break
        Message("Note:Type 'go back' if you would like to go back from any operation","-")
        if Name is None:
            Argument_Entered=False
            while True:
                Name=" ".join(input("\n\t Enter product's name : ").strip().lower().title().split())
                if Name=="":
                    Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
                    continue
                else:
                    break
        else:
            Argument_Entered=True
        if Name=="Go Back":
            Message("OPERATION CANCELLED!","-")
            break
        NameFiller,PriceFiller,DateFiller="","",""
        Found=False
        for i in list(Data.items()):
            if Name==i[1][0]:
                Found,Updated_Data,Update_Decision,key=True,[i[1][0],i[1][1],i[1][2],"Barcode"],"YES",i[0]
                while Update_Decision.startswith("Y"):
                    Update_Option=input("""
         Which detail would you like to edit :
             1.Name of the product
             2.Price of the product
             3.Production date of the product
             4.Exit
         Enter option(1-4): """).strip().lower().replace(".","").replace("'","").replace(",","").replace(" ","")
                    if Update_Option in ["1","name","nameoftheproduct","1nameoftheproduct","1name"]:
                        while True:
                            New_Name=" ".join(input("\n\t Enter the new name of the product : ").strip().lower().title().split())
                            if New_Name=="":
                                Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
                                continue
                            else:
                                break
                        if New_Name=="Go Back":
                            Message("OPERATION CANCELLED!","-")
                            continue
                        if New_Name==Name:
                            if NameFiller=="Updated ":
                                Message("YOU'VE ENTERED THE EXISTING NAME. ANY RECENT CHANGES TO THE NAME FIELD HAVE BEEN DISCARDED","-")
                            elif NameFiller=="":
                                Message("YOU'VE ENTERED THE EXISTING NAME, THEREFORE NO CHANGES WERE MADE!","-")
                            Updated_Data[0],NameFiller=New_Name,""
                            continue
                        if New_Name==Updated_Data[0]:
                            Message("YOU'VE ENTERED THE RECENTLY CHANGED NAME, THEREFORE NO CHANGES WERE MADE!","-")
                            continue
                        for v in Data:
                            if (Data.get(v))[0]==New_Name:
                                Message(f"PRODUCT WITH THE NAME '{New_Name}' ALREADY EXISTS!",":")
                                break
                        else:
                            Updated_Data[0],NameFiller=New_Name,"Updated "
                        if (Data.get(v))[0]==New_Name:
                            continue
                    elif Update_Option in ["2","priceoftheproduct","price","2priceoftheproduct","2price"]:
                        while True:
                            New_Price="".join(input("\n\t Enter the new price of the product (Only Digits) : ").strip().upper().split())
                            if New_Price=="GOBACK":
                                break
                            Price_Status,New_Price=Validate_Price(New_Price)
                            if Price_Status==True:
                                break
                        if New_Price=="GOBACK":
                            Message("OPERATION CANCELLED!","-")
                            continue
                        if New_Price==Updated_Data[1]:
                            Message("YOU'VE ENTERED THE EXISTING PRICE, THEREFORE NO CHANGES WERE MADE!","-")
                            continue
                        elif New_Price==i[1][1]:
                            Message("YOU'VE ENTERED THE EXISTING PRICE. ANY RECENT CHANGES TO THE PRICE FIELD HAVE BEEN DISCARDED","-")
                            PriceFiller=""
                            Updated_Data[1]=New_Price
                            continue
                        Updated_Data[1],PriceFiller=New_Price,"Updated "
                    elif Update_Option in ["3","productiondateoftheproduct","productiondate","date","3productiondateoftheproduct","3productiondate","3date"]:
                        while True:
                            New_Date=input("\n\t Enter the new production date of the product (Enter in dd/mm/yy or text format [Example: 1st Jan 2025]) : ").strip()
                            if New_Date=="":
                                Message("ENTERED FIELD IS EMPTY, PLEASE ENTER A VALID INPUT!",":")
                                continue
                            if "".join(New_Date.upper().split())=="GOBACK":
                                break
                            New_Date,Valid_Date=Validate_Date(New_Date)
                            if Valid_Date:
                                break
                            elif Valid_Date==False:
                                Message("INVALID INPUT! [Enter in dd/mm/yy or text format (Example : 1st Jan 2025)]",":")
                            elif Valid_Date==None:
                                Message("INVALID DATE! [The date you have entered does not exist!]",":")
                        if "".join(New_Date.upper().split())=="GOBACK":
                            Message("OPERATION CANCELLED!","-")
                            continue
                        if New_Date==Updated_Data[2]:
                            Message("YOU'VE ENTERED THE EXISTING DATE, THEREFORE NO CHANGES WERE MADE!","-")
                            continue
                        elif New_Date==i[1][2]:
                            Message("YOU'VE ENTERED THE EXISTING DATE. ANY RECENT CHANGES TO THE DATE FIELD HAVE BEEN DISCARDED","-")
                            DateFiller=""
                            Updated_Data[2]=New_Date
                            continue
                        elif Valid_Date:
                            Updated_Data[2],DateFiller=New_Date,"Updated "
                    elif Update_Option in ["4","exit","4exit","quit","3quit"]:
                        Update_Decision="NO"
                    else:
                        Message("PLEASE ENTER A VALID OPTION (1-4)!",":")
                        continue
                    if Update_Option in ["1","2","3"]:
                        Update_Decision=input("\n\t Would you like to make another change to the same product ? Yes/No ").strip().upper()
        if Found==False:
            Message("PRODUCT NOT FOUND!",":")
        else:
            if "Updated " not in [NameFiller,PriceFiller,DateFiller]:
                Message("NO CHANGES MADE!","-")
                break
            del Data[key]
            Barcode,Barcode_Binary,Barcode_Decimal=Barcode_Generator(Updated_Data[0],Updated_Data[1],Updated_Data[2])
            Data[Barcode_Binary]=[Updated_Data[0],Updated_Data[1],Updated_Data[2],Barcode]
            Print_Barcode(Updated_Data[0],Updated_Data[1],Updated_Data[2],Barcode,hex(Barcode_Decimal)[2:].upper(),Name_Filler=NameFiller,Price_Filler=PriceFiller,Date_Filler=DateFiller)
            Save_Overall_Data(Data)
        if Argument_Entered:
            print()
            break
        Decision=input("\n\t Would you like to make changes to another product's data? Yes/No ").strip().upper()
        Name=None
def list_items(Data,Employee=False):
    Data=Sort_Items(Data)
    if len(Data)==0:
        Message("NO DATA FOUND!",":")
    else:
        for key,value in Data.items():
            Print_Barcode(value[0],value[1],value[2],value[3],hex(int(key,2))[2:].upper())
    if Employee==True:
        logs("Employee has listed all the products")
def Main_Menu():
    while True:
        Menu_Decision=input(f"""

 {"="*100}

  Which of the following operations would you like to perform ?
   1.Create Barcode
   2.Search for product's Barcode
   3.Update product's Barcode
   4.Delete product's Barcode
   5.Read the list of Name, Price and Production Date of all items
   6.Exit
  Enter an Option from 1-6 : """).strip().lower().replace(".","").replace("'","").replace(",","").replace(" ","")
        print("\n","="*100,"\n")
        if Menu_Decision in ["1","createbarcode","create","1createbarcode","1create"]:
            Create_Barcode(Data)
        elif Menu_Decision in ["2","searchforproductsbarcode","search","2searchforproductsbarcode","2search"]:
            Search_Barcode(Data)
        elif Menu_Decision in ["3","updateproductsbarcode","update","3updateproductsbarcode","3update"]:
            Update_Barcode(Data)
        elif Menu_Decision in ["4","deleteproductsbarcode","delete","4deleteproductsbarcode","4delete"]:
            Delete_Barcode(Data)
        elif Menu_Decision in ["5","readthelistofnamepriceandproductiondateofallitems","read","5readthelistofnamepriceandproductiondateofallitems","5read"]:
            list_items(Data)
        elif Menu_Decision in ["6","exit","6exit","quit","6quit"]:
            logs("Logged out")
            break
        else:
            Message("INVALID OPTION!",":")
def Employee_Menu():
    while True:
        Menu_Decision=input(f"""

 {"="*100}

  Which of the following operations would you like to perform ?
   1.Search for product's Barcode
   2.Read the list of Name, Price and Production Date of all items
   3.Exit
  Enter an Option from 1-3 : """).strip().lower().replace(".","").replace("'","").replace(",","").replace(" ","")
        print("\n","="*100,"\n")
        if Menu_Decision in ["1","searchforproductsbarcode","search","1searchforproductsbarcode","1search"]:
            Search_Barcode(Data,Employee=True)
        elif Menu_Decision in ["2","readthelistofnamepriceandproductiondateofallitems","read","2readthelistofnamepriceandproductiondateofallitems","2read"]:
            list_items(Data,Employee=True)
        elif Menu_Decision in ["3","exit","3exit","quit","3quit"]:
            logs("Employee Logged out")
            break
        else:
            Message("INVALID OPTION!",":")
import csv
def CSV_File_Saver(Data):
    #The data is saved in the csv file for the user access/viewability only - the program does not read from it 
    #we do the reading part from the binary file as it is quicker
    with open("Barcode Data.csv","w",newline="",encoding="utf-8") as CSV_File:  #'utf-8' is used for unicode character support
        CSV_writer=csv.writer(CSV_File)
        Data_items=list(Data.items())
        CSV_writer.writerow(["Name","Price","Date of Production","Barcode","Binary Value"])
        for i in Data_items:
            CSV_writer.writerow([i[1][0],i[1][1],i[1][2],i[1][3],i[0]])
import pickle
def Binary_File_Saver(Data):
    with open("Barcode Data.dat","wb") as File:
        pickle.dump(Data,File)
def Save_Overall_Data(Data):
    Data=Sort_Items(Data)
    Binary_File_Saver(Data)
    CSV_File_Saver(Data)
def logs(status):
    from datetime import datetime
    time=datetime.now().strftime("%d/%m/%y %H:%M:%S")
    try:
        with open("logs.txt","r+") as File:
            Prev_Data=File.readlines()
            Record=len(Prev_Data)+1
            File.seek(0)
            File.writelines(Prev_Data+[f"Record#{Record} : {status} at {time}\n"])
    except (EOFError,FileNotFoundError):
        with open("logs.txt","w") as File:
            File.write(f"Record#1 : {status} at {time}\n")
#Login
for attempt in range(3):
    #This allows the user for 3 attempts
    Admin_Password="5e6d49f2e51518f1ca87ff5daafb22eecfad6f76ad4552b379a8a2c03baacec4"   #Password for admin : adMin@123 -----------+------>Password is given over here for the project submission
    Employee_Password="a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e"    #Password for employee : Hello World --+
    Get_Password=hashlib.sha256(input(" Enter Password (Mentioned in README.md): ").encode('utf-8')).hexdigest()    #This type of password check is done to ensure encryption of passwords because anyone that has access to the code can break into the program easily
    if Get_Password==Admin_Password:
        logs("Admin Logged in")
        break
    elif Get_Password==Employee_Password:
        logs("Employee Logged in")
        break
    else:
        Message("Incorrect Password!",":")
        logs(f"Incorrect Password Attempt {attempt+1}")
    if attempt==2:
        Message("TOO MANY PASSWORD ATTEMPTS!",":")
        raise Exception
try:
    Data=dict()
    with open("Barcode Data.dat","rb") as File:
        Data=pickle.load(File)
except (EOFError,FileNotFoundError):
    if Get_Password==Admin_Password:    
        Data=dict()
        Create_Barcode(Data)
    else:
        Message("No Data Found!","-")
        logs("Employee Logged out")
else:
    if len(Data)==0:
        if Get_Password==Admin_Password:
            Create_Barcode(Data)
        else:
            Message("No Data Found!","-")
            logs("Employee Logged out")
if Get_Password==Admin_Password:
    Main_Menu()
if Get_Password==Employee_Password and len(Data)!=0:
    Employee_Menu()
print(" ","="*100)
Message("Thank You!","-")
